POST http://localhost:3333/register
Content-Type: application/json

{
    "name": "joao",
    "email": "joao@joao.com",
    "password": "joanaw",
    "lastname": "Abreu",
    "birth": "20/09/2002",
    "age": 21,
    "gender": "masculino",
    "father": "Mario Abreu",
    "mother": "Maria Abreu",
    "address": "Unknow Street"
}

### 
POST http://localhost:3333/auth
Content-Type: application/json

{
    "email": "joao@joao.com",
    "password": "joanaw"
}

### 
DELETE http://localhost:3333/delete-user/clr9fmg5j0000j7ul460mlbi9

###
PUT  http://localhost:3333/update-user/clr9fmg5j0000j7ul460mlbi9
Content-Type: application/json

{
    "name": "Joao",
    "email": "joao@test.com",
    "password": "nodejs",
    "lastname": "Abreu",
    "birth": "20/09/2002",
    "age": 21,
    "gender": "masculino",
    "father": "Mario Abreu",
    "mother": "Maria Abreu",
    "address": "Know Street"
}

###
GET http://localhost:3333/users

### 
GET http://localhost:3333/resource
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiam9hbyIsImVtYWlsIjoiam9hb0Bqb2FvLmNvbSIsInN1YiI6ImNscjlmbjhndzAwMDFqN3VsamJ1dmppOHgiLCJpYXQiOjE3MDQ5OTEwNTQsImV4cCI6MTcwNDk5MTY1NH0.x19KRDchIhAVxIFI0GeRqXHOEkCRUtrGyi-dJeNDAM4